home:
    path:     /
    defaults: { _controller: MainBundle:Default:main }
    
page1:
    path:     /prueba1/{age}
    defaults: { _controller: MainBundle:Default:page1, age: 18 }
    requirements:
        age: \d+
    
page2:
    path:     /prueba2/{name}
    defaults: { _controller: MainBundle:Default:page2, name: sscenter }
    
page3:
    path:     /prueba3/{hour}
    defaults: { _controller: MainBundle:Default:page3, hour: 16 }
    
page4:
    path:     /prueba4
    defaults: { _controller: MainBundle:Default:page4 }
    
page5:
    path:     /prueba5/{val1}/{val2}
    defaults: { _controller: MainBundle:Default:page5, val1: 15 , val2: 10 }



