main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

capacitation:
    resource: "@CapacitationBundle/Resources/config/routing.yml"
    prefix:   /PRUEBA/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
