contactform:
    path:     /
    defaults: { _controller: "SsCenterMainBundle:ContactForm:index" }

contactform_show:
    path:     /{id}/show
    defaults: { _controller: "SsCenterMainBundle:ContactForm:show" }

contactform_new:
    path:     /new
    defaults: { _controller: "SsCenterMainBundle:ContactForm:new" }

contactform_create:
    path:     /create
    defaults: { _controller: "SsCenterMainBundle:ContactForm:create" }
    methods:  POST

contactform_edit:
    path:     /{id}/edit
    defaults: { _controller: "SsCenterMainBundle:ContactForm:edit" }

contactform_update:
    path:     /{id}/update
    defaults: { _controller: "SsCenterMainBundle:ContactForm:update" }
    methods:  [POST, PUT]

contactform_delete:
    path:     /{id}/delete
    defaults: { _controller: "SsCenterMainBundle:ContactForm:delete" }
    methods:  [POST, DELETE]
