SsCenter\MainBundle\Entity\Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
    field:
        name:
            type: string
            length: 50
        phone:
            type: string
            length: 15
        address:
            type: string
            length: 50
        nit:
            type: string
            length: 15
    oneToMany:
        contact: 
            targetEntity : SsCenter\MainBundle\Entity\ContacForm
            mappedBy: client
            