SsCenter\MainBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            length: 10
        name: 
            type: string
            length: 50
        notes:
            type: text
            nullable: true
            
        