SsCenter\MainBundle\Entity\StatusNotes:
    type: entity
    table: status_notes
    id:
        id:
            type: integer 
            generator: { strategy: IDENTITY }
    fields:
        name:
            type: string
            unique: true
            length: 100
            comment: "Name of status notes"
        description:
            type: text
            nullable: true
            comment: "Description of the status"
            
            
    