SsCenter\MainBundle\Entity\StatusNotes:
    type: entity
    table: status_notes
    id:
        id: integer
        generator: { strategy: IDENTITY }
    fields:
        name:
            type: string
            unique: true
            length: 100
            comment: 'Name of status notes'
        description:
            type: text
            nullabe: true
            comment: 'Description of the status'