SsCenter\MainBundle\Entity\StatusTicket:
    type: entity
    table: status_ticket
    id:
        id: integer
        generator: { strategy: AUTO }
    fields:
        name:
            type: string
            
            length: 100
            comment: 'Name of status'
        description:
            type: text
            nullabe: true
            comment: 'Description of the status'