SsCenter\MainBundle\Entity\StatusNotes:
    type: entity
    table: status_notes
    id:
        id: 
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
            comment: 'Name of status notes'
        description:
            type: text
            nullabe: true
            comment: 'Description of the status'
    oneToMany:
        reports:
            targetEntity: SsCenter\MainBundle\Entity\Report
            mappedBy: statusNotes
            
            