SsCenter\MainBundle\Entity\TicketType:
    type: entity
    table: ticket_type
    id:
        id: integer
        generator: { strategy: IDENTITY }
    fields:
        name:
            type: string
            unique: true
            length: 100
            comment: 'Name of status'
        description:
            type: text
            nullabe: true
            comment: 'Description of the status'