SsCenter\MainBundle\Entity\TicketType:
    type: entity
    table: ticket_type
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            
            length: 100
            comment: 'Name of status'
        description:
            type: text
            nullabe: true
            comment: 'Description of the status'
    oneToMany:
        tickets:
            targetEntity: SsCenter\MainBundle\Entity\Ticket
            mappedBy: ticketType