SsCenter\MainBundle\Entity\Ticket:
    type: entity
    table: ticket
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        code: 
            type: string
             
            length: 10
        title:
            type: string
        description: 
            type: text
        creationDate:
            type: datetime
            column: creation_date
        closeDate: 
            type: datetime
            column: close_date
            nullable: true
        fileName:
            type: string
            column: file_name
            nullable: true
    manyToOne:
        client:
            targetEntity: SsCenter\MainBundle\Entity\Client
            inversedBy: tickets
            joinColumn:
                name: id_client
                referencedColumnName: id
        product:
            targetEntity: SsCenter\MainBundle\Entity\Product
            inversedBy: tickets
            joinColumn:
                name: id_product
                referencedColumnName: id
        ticketType:
            targetEntity: SsCenter\MainBundle\Entity\TicketType
            inversedBy: tickets
            joinColumn:
                name: ticket_type_id
                referencedColumnName: id
        statusTicket:
            targetEntity: SsCenter\MainBundle\Entity\StatusTicket
            inversedBy: tickets
            joinColumn:
                name: status_ticket_id
                referencedColumName: id
        userCreator:
            targetEntity:  Application\Sonata\UserBundle\Entity\User
            joinColumn: 
                name: id_user_creator
                referencedColumnName: id
        userAssigned:
            targetEntity:  Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: id_user_assigned
                referencedColumnName: id
    manyToMany:
        reports:
            targetEntity: SsCenter\MainBundle\Entity\Report
            inversedBy: tickets
            joinTable:
                name: ticket_report
                joinColumns:
                    id_ticket:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_report:
                        referencedColumnName: id

                
            
        
    
     
            
            